### Read all movies with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/movies

### Read all movies shorter or equal to 148min 
GET {{baseUrl}}/movies/?minimum-duration=148

### Read a single movie
GET {{baseUrl}}/movies/2

### Create a movie
POST {{baseUrl}}/movies
Content-Type: application/json

{
    "title": "Avatar",
    "director": "James Cameron",
    "duration": 162,
    "budget": 237000000,
    "description": "A paraplegic Marine on an alien planet becomes torn between following his orders and protecting the world he feels is his home.",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg"
}

### Read all movies which the name starts with I
GET {{baseUrl}}/movies/?title=the

### Delete a drink
DELETE  {{baseUrl}}/movies/3

### Modify a movie
PATCH  {{baseUrl}}/movies/3
Content-Type: application/json

{
    "title": "Naruto",
    "director": "Uzumaki",
    "duration": 0
}

### Replace a movie
PUT  {{baseUrl}}/movies/1
Content-Type: application/json

{
    "title": "One Piece",
    "director": "Eichiro Oda",
    "duration": 256
}
//c'est quoi unknown ? 
//comment le patch fontionnce avec le fichier types ? 